[tool.poetry]
name = "appinspector"
version = "0.1.0"
description = "client for app-inspector.devsleep.com"
authors = ["codeskyblue <codeskyblue@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = {extras = ["all"], version = "^0.109.2"}
uvicorn = {extras = ["standard"], version = "^0.27.1"}
pillow = "^10.2.0"
adbutils = "^2.2.1"

[tool.poetry.scripts]
appinspector = "appinspector.__main__:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.1"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
